// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file api/v1beta1/translate.proto (package api.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HealthzRequest, HealthzResponse } from "./translate_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v1beta1.TranslationService
 */
export const TranslationService = {
  typeName: "api.v1beta1.TranslationService",
  methods: {
    /**
     * @generated from rpc api.v1beta1.TranslationService.healthz
     */
    healthz: {
      name: "healthz",
      I: HealthzRequest,
      O: HealthzResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

