// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file api/v1beta1/translate.proto (package api.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1beta1/translate.proto.
 */
export const file_api_v1beta1_translate: GenFile = /*@__PURE__*/
  fileDesc("ChthcGkvdjFiZXRhMS90cmFuc2xhdGUucHJvdG8SC2FwaS52MWJldGExIhAKDkhlYWx0aHpSZXF1ZXN0IkQKD0hlYWx0aHpSZXNwb25zZRIPCgdoZWFsdGh5GAEgASgIEg8KB21lc3NhZ2UYAiABKAkSDwoHdmVyc2lvbhgDIAEoCTJaChJUcmFuc2xhdGlvblNlcnZpY2USRAoHSGVhbHRoehIbLmFwaS52MWJldGExLkhlYWx0aHpSZXF1ZXN0GhwuYXBpLnYxYmV0YTEuSGVhbHRoelJlc3BvbnNlQj5aPGdpdGh1Yi5jb20vbGVtb24tbWludC9sbG0tdHJhbnNsYXRpb24vYXBpL3YxYmV0YTE7YXBpdjFiZXRhMWIGcHJvdG8z");

/**
 * @generated from message api.v1beta1.HealthzRequest
 */
export type HealthzRequest = Message<"api.v1beta1.HealthzRequest"> & {
};

/**
 * Describes the message api.v1beta1.HealthzRequest.
 * Use `create(HealthzRequestSchema)` to create a new message.
 */
export const HealthzRequestSchema: GenMessage<HealthzRequest> = /*@__PURE__*/
  messageDesc(file_api_v1beta1_translate, 0);

/**
 * @generated from message api.v1beta1.HealthzResponse
 */
export type HealthzResponse = Message<"api.v1beta1.HealthzResponse"> & {
  /**
   * @generated from field: bool healthy = 1;
   */
  healthy: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string version = 3;
   */
  version: string;
};

/**
 * Describes the message api.v1beta1.HealthzResponse.
 * Use `create(HealthzResponseSchema)` to create a new message.
 */
export const HealthzResponseSchema: GenMessage<HealthzResponse> = /*@__PURE__*/
  messageDesc(file_api_v1beta1_translate, 1);

/**
 * @generated from service api.v1beta1.TranslationService
 */
export const TranslationService: GenService<{
  /**
   * @generated from rpc api.v1beta1.TranslationService.Healthz
   */
  healthz: {
    methodKind: "unary";
    input: typeof HealthzRequestSchema;
    output: typeof HealthzResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1beta1_translate, 0);

