// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file translate/v1beta1/translate.proto (package translate.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file translate/v1beta1/translate.proto.
 */
export const file_translate_v1beta1_translate: GenFile = /*@__PURE__*/
  fileDesc("CiF0cmFuc2xhdGUvdjFiZXRhMS90cmFuc2xhdGUucHJvdG8SEXRyYW5zbGF0ZS52MWJldGExIhAKDkhlYWx0aHpSZXF1ZXN0IkQKD0hlYWx0aHpSZXNwb25zZRIPCgdoZWFsdGh5GAEgASgIEg8KB21lc3NhZ2UYAiABKAkSDwoHdmVyc2lvbhgDIAEoCTJmChJUcmFuc2xhdGlvblNlcnZpY2USUAoHSGVhbHRoehIhLnRyYW5zbGF0ZS52MWJldGExLkhlYWx0aHpSZXF1ZXN0GiIudHJhbnNsYXRlLnYxYmV0YTEuSGVhbHRoelJlc3BvbnNlQlBaTmdpdGh1Yi5jb20vbGVtb24tbWludC9sbG0tdHJhbnNsYXRpb24vcHJvdG8vdHJhbnNsYXRlL3YxYmV0YTE7dHJhbnNsYXRldjFiZXRhMWIGcHJvdG8z");

/**
 * @generated from message translate.v1beta1.HealthzRequest
 */
export type HealthzRequest = Message<"translate.v1beta1.HealthzRequest"> & {
};

/**
 * Describes the message translate.v1beta1.HealthzRequest.
 * Use `create(HealthzRequestSchema)` to create a new message.
 */
export const HealthzRequestSchema: GenMessage<HealthzRequest> = /*@__PURE__*/
  messageDesc(file_translate_v1beta1_translate, 0);

/**
 * @generated from message translate.v1beta1.HealthzResponse
 */
export type HealthzResponse = Message<"translate.v1beta1.HealthzResponse"> & {
  /**
   * @generated from field: bool healthy = 1;
   */
  healthy: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string version = 3;
   */
  version: string;
};

/**
 * Describes the message translate.v1beta1.HealthzResponse.
 * Use `create(HealthzResponseSchema)` to create a new message.
 */
export const HealthzResponseSchema: GenMessage<HealthzResponse> = /*@__PURE__*/
  messageDesc(file_translate_v1beta1_translate, 1);

/**
 * @generated from service translate.v1beta1.TranslationService
 */
export const TranslationService: GenService<{
  /**
   * @generated from rpc translate.v1beta1.TranslationService.Healthz
   */
  healthz: {
    methodKind: "unary";
    input: typeof HealthzRequestSchema;
    output: typeof HealthzResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_translate_v1beta1_translate, 0);

