// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file translate/v1beta1/translate.proto (package translate.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HealthzRequest, HealthzResponse } from "./translate_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service translate.v1beta1.TranslationService
 */
export const TranslationService = {
  typeName: "translate.v1beta1.TranslationService",
  methods: {
    /**
     * @generated from rpc translate.v1beta1.TranslationService.Healthz
     */
    healthz: {
      name: "Healthz",
      I: HealthzRequest,
      O: HealthzResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

