// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: api/v1beta1/translate.proto

package apiv1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_UNSPECIFIED Language = 0
	Language_ENGLISH     Language = 1
	Language_SPANISH     Language = 2
	Language_CHINESE     Language = 3
	Language_KOREAN      Language = 4
	Language_JAPANESE    Language = 5
	Language_GERMAN      Language = 6
	Language_RUSSIAN     Language = 7
	Language_FRENCH      Language = 8
	Language_DUTCH       Language = 9
	Language_ITALIAN     Language = 10
	Language_INDONESIAN  Language = 11
	Language_PORTUGUESE  Language = 12
	Language_TAIWANESE   Language = 13
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "ENGLISH",
		2:  "SPANISH",
		3:  "CHINESE",
		4:  "KOREAN",
		5:  "JAPANESE",
		6:  "GERMAN",
		7:  "RUSSIAN",
		8:  "FRENCH",
		9:  "DUTCH",
		10: "ITALIAN",
		11: "INDONESIAN",
		12: "PORTUGUESE",
		13: "TAIWANESE",
	}
	Language_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ENGLISH":     1,
		"SPANISH":     2,
		"CHINESE":     3,
		"KOREAN":      4,
		"JAPANESE":    5,
		"GERMAN":      6,
		"RUSSIAN":     7,
		"FRENCH":      8,
		"DUTCH":       9,
		"ITALIAN":     10,
		"INDONESIAN":  11,
		"PORTUGUESE":  12,
		"TAIWANESE":   13,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1beta1_translate_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_api_v1beta1_translate_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_api_v1beta1_translate_proto_rawDescGZIP(), []int{0}
}

type LLMOptions_Provider int32

const (
	LLMOptions_UNSPECIFIED LLMOptions_Provider = 0
	LLMOptions_SERVER      LLMOptions_Provider = 1
	LLMOptions_AISTUDIO    LLMOptions_Provider = 2
	LLMOptions_OPENAI      LLMOptions_Provider = 3
	LLMOptions_ANTHROPIC   LLMOptions_Provider = 4
)

// Enum value maps for LLMOptions_Provider.
var (
	LLMOptions_Provider_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SERVER",
		2: "AISTUDIO",
		3: "OPENAI",
		4: "ANTHROPIC",
	}
	LLMOptions_Provider_value = map[string]int32{
		"UNSPECIFIED": 0,
		"SERVER":      1,
		"AISTUDIO":    2,
		"OPENAI":      3,
		"ANTHROPIC":   4,
	}
)

func (x LLMOptions_Provider) Enum() *LLMOptions_Provider {
	p := new(LLMOptions_Provider)
	*p = x
	return p
}

func (x LLMOptions_Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LLMOptions_Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1beta1_translate_proto_enumTypes[1].Descriptor()
}

func (LLMOptions_Provider) Type() protoreflect.EnumType {
	return &file_api_v1beta1_translate_proto_enumTypes[1]
}

func (x LLMOptions_Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LLMOptions_Provider.Descriptor instead.
func (LLMOptions_Provider) EnumDescriptor() ([]byte, []int) {
	return file_api_v1beta1_translate_proto_rawDescGZIP(), []int{3, 0}
}

type HealthzRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1beta1_translate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_translate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_translate_proto_rawDescGZIP(), []int{0}
}

type HealthzResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Healthy bool   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1beta1_translate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_translate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_translate_proto_rawDescGZIP(), []int{1}
}

func (x *HealthzResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthzResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthzResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type LLMCredentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
}

func (x *LLMCredentials) Reset() {
	*x = LLMCredentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1beta1_translate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMCredentials) ProtoMessage() {}

func (x *LLMCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_translate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMCredentials.ProtoReflect.Descriptor instead.
func (*LLMCredentials) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_translate_proto_rawDescGZIP(), []int{2}
}

func (x *LLMCredentials) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type LLMOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider    LLMOptions_Provider `protobuf:"varint,10,opt,name=provider,proto3,enum=api.v1beta1.LLMOptions_Provider" json:"provider,omitempty"`
	Credentials *LLMCredentials     `protobuf:"bytes,20,opt,name=credentials,proto3,oneof" json:"credentials,omitempty"`
}

func (x *LLMOptions) Reset() {
	*x = LLMOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1beta1_translate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMOptions) ProtoMessage() {}

func (x *LLMOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_translate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMOptions.ProtoReflect.Descriptor instead.
func (*LLMOptions) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_translate_proto_rawDescGZIP(), []int{3}
}

func (x *LLMOptions) GetProvider() LLMOptions_Provider {
	if x != nil {
		return x.Provider
	}
	return LLMOptions_UNSPECIFIED
}

func (x *LLMOptions) GetCredentials() *LLMCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type TranslateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text           string      `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`
	TargetLanguage Language    `protobuf:"varint,20,opt,name=target_language,json=targetLanguage,proto3,enum=api.v1beta1.Language" json:"target_language,omitempty"`
	Options        *LLMOptions `protobuf:"bytes,30,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1beta1_translate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1beta1_translate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1beta1_translate_proto_rawDescGZIP(), []int{4}
}

func (x *TranslateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateRequest) GetTargetLanguage() Language {
	if x != nil {
		return x.TargetLanguage
	}
	return Language_UNSPECIFIED
}

func (x *TranslateRequest) GetOptions() *LLMOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_api_v1beta1_translate_proto protoreflect.FileDescriptor

var file_api_v1beta1_translate_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x22, 0x10, 0x0a, 0x0e, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5f, 0x0a, 0x0f,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x29, 0x0a,
	0x0e, 0x4c, 0x4c, 0x4d, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x22, 0xf0, 0x01, 0x0a, 0x0a, 0x4c, 0x4c, 0x4d,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3c, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x4c, 0x4d, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x4c, 0x4d, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x88, 0x01, 0x01, 0x22, 0x50, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x49, 0x53, 0x54, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x50, 0x45, 0x4e, 0x41, 0x49, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09,
	0x41, 0x4e, 0x54, 0x48, 0x52, 0x4f, 0x50, 0x49, 0x43, 0x10, 0x04, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x10,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x3e, 0x0a, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2e, 0x4c, 0x4c, 0x4d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2a, 0xc8, 0x01, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x4e, 0x47, 0x4c, 0x49, 0x53, 0x48,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x50, 0x41, 0x4e, 0x49, 0x53, 0x48, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x53, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06,
	0x4b, 0x4f, 0x52, 0x45, 0x41, 0x4e, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x41, 0x50, 0x41,
	0x4e, 0x45, 0x53, 0x45, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x45, 0x52, 0x4d, 0x41, 0x4e,
	0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x53, 0x53, 0x49, 0x41, 0x4e, 0x10, 0x07, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x52, 0x45, 0x4e, 0x43, 0x48, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05, 0x44,
	0x55, 0x54, 0x43, 0x48, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x54, 0x41, 0x4c, 0x49, 0x41,
	0x4e, 0x10, 0x0a, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4e, 0x44, 0x4f, 0x4e, 0x45, 0x53, 0x49, 0x41,
	0x4e, 0x10, 0x0b, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x4f, 0x52, 0x54, 0x55, 0x47, 0x55, 0x45, 0x53,
	0x45, 0x10, 0x0c, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x41, 0x49, 0x57, 0x41, 0x4e, 0x45, 0x53, 0x45,
	0x10, 0x0d, 0x32, 0x5a, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x7a, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e,
	0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x6d,
	0x6f, 0x6e, 0x2d, 0x6d, 0x69, 0x6e, 0x74, 0x2f, 0x6c, 0x6c, 0x6d, 0x2d, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1beta1_translate_proto_rawDescOnce sync.Once
	file_api_v1beta1_translate_proto_rawDescData = file_api_v1beta1_translate_proto_rawDesc
)

func file_api_v1beta1_translate_proto_rawDescGZIP() []byte {
	file_api_v1beta1_translate_proto_rawDescOnce.Do(func() {
		file_api_v1beta1_translate_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1beta1_translate_proto_rawDescData)
	})
	return file_api_v1beta1_translate_proto_rawDescData
}

var file_api_v1beta1_translate_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1beta1_translate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1beta1_translate_proto_goTypes = []any{
	(Language)(0),            // 0: api.v1beta1.Language
	(LLMOptions_Provider)(0), // 1: api.v1beta1.LLMOptions.Provider
	(*HealthzRequest)(nil),   // 2: api.v1beta1.HealthzRequest
	(*HealthzResponse)(nil),  // 3: api.v1beta1.HealthzResponse
	(*LLMCredentials)(nil),   // 4: api.v1beta1.LLMCredentials
	(*LLMOptions)(nil),       // 5: api.v1beta1.LLMOptions
	(*TranslateRequest)(nil), // 6: api.v1beta1.TranslateRequest
}
var file_api_v1beta1_translate_proto_depIdxs = []int32{
	1, // 0: api.v1beta1.LLMOptions.provider:type_name -> api.v1beta1.LLMOptions.Provider
	4, // 1: api.v1beta1.LLMOptions.credentials:type_name -> api.v1beta1.LLMCredentials
	0, // 2: api.v1beta1.TranslateRequest.target_language:type_name -> api.v1beta1.Language
	5, // 3: api.v1beta1.TranslateRequest.options:type_name -> api.v1beta1.LLMOptions
	2, // 4: api.v1beta1.TranslationService.healthz:input_type -> api.v1beta1.HealthzRequest
	3, // 5: api.v1beta1.TranslationService.healthz:output_type -> api.v1beta1.HealthzResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1beta1_translate_proto_init() }
func file_api_v1beta1_translate_proto_init() {
	if File_api_v1beta1_translate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1beta1_translate_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HealthzRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1beta1_translate_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HealthzResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1beta1_translate_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LLMCredentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1beta1_translate_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LLMOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1beta1_translate_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TranslateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1beta1_translate_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1beta1_translate_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1beta1_translate_proto_goTypes,
		DependencyIndexes: file_api_v1beta1_translate_proto_depIdxs,
		EnumInfos:         file_api_v1beta1_translate_proto_enumTypes,
		MessageInfos:      file_api_v1beta1_translate_proto_msgTypes,
	}.Build()
	File_api_v1beta1_translate_proto = out.File
	file_api_v1beta1_translate_proto_rawDesc = nil
	file_api_v1beta1_translate_proto_goTypes = nil
	file_api_v1beta1_translate_proto_depIdxs = nil
}
